### ISSUE TITLE
Probando a hacer una issue: Primera duda ¿Auto format en light table?

### ISSUE THREAD

**Issue by mi-mina** [Grupete/jau-tu#1]
duda muy tonta para hacer una prueba

¿Alguien sabe si hay algo parecido a auto-format en Light Table? Es decir, algo que te reordene el código y te lo ponga bonito... me refiero a los tabuladores y eso. En processing hay algo así y lo echo de menos. ;)

**Comment by mi-mina** [comment]
¡Qué guapo! Es como un chat! Y se pueden poner etiquetas!

**Comment by mi-mina** [comment]
Pues añado aquí otra cosa que tiene que ver con esto, también muy tonto.
Me ha pasado, pero sólo a veces, en Light Table, que al escribir    **'**   , (el apóstrofe que se usa para hacer un _quote_, como para escribir `'(1 2 3)`), me escribe []. Es decir, no me deja escribir un apóstrofe y me pone dos corchetes automáticamente. ¿Le ha pasado a alguien?

**Comment by tangrammer** [comment]
vaya con el Light Table, es tan fácil que no te deja escribir :)
Yo soy del emac's team, lo siento pero no puedo ayudar aquí (aunque echaré unas google searchs around)

**Comment by danigb** [comment]
Ejem... yo uso VIM, así que tampoco puedo ayudar. Quizá deberíamos probar, en vez de LightTable, la otra opción que comentaba Juan en la reu (basada en IntelliJ) que me pareció entender que _aun_ es gratis ;-)

**Comment by tangrammer** [comment]
el mundo es un pañuelo!
https://github.com/LightTable/LightTable/issues/1599

y aquí la solución
https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-prevent-lighttable-from-automatically-filling-in-the-pair-to-

**Comment by mi-mina** [comment]
ole! gracias! la verdad es que también podía yo haber hecho la búsqueda! jejejej... es que me he emocionao con las issues. Bueno pues issue resuelta! La cierro no?
Yo de momento voy bien con light table, ya me he hecho un poco a él. Si acaso más adelante puedo dar el salto a emacs o vim. De hecho light table tiene un pluging de VIM, que no sé para qué será... a lo mejor para hacerlo más parecido a vim... Bueno! esto funciona! comunidad de aprendizaje viento en popa!
